name: Python application

on: [push]

jobs:
  build:
    runs-on: blacksmith-4vcpu-ubuntu-2204
    steps:
    - uses: actions/checkout@v2
    - uses: useblacksmith/setup-python@v6
      with:
        python-version: '3.10'
    - run: pip install pytest
    - run: pytest
